### ISSUE TITLE
it wont embed gif in discord

### ISSUE THREAD

**Issue by banana-man95** [ThePlasmaRailgun/cdn.dlcordapp.com#13]
when trying to put https://dlcordapp.com/attachments/697482601782444032/782991535364505630/ezgif-4-977210ec934b.gif into discord. it doesn't embed into discord. it's just the link. how do I fix this

**Comment by NovaLogicDev** [comment]
Your gif probably no longer exists meaning the message you got the original link from has probably been deleted.

**Comment by fionafibration** [comment]
Yes. the file doesn't exist anymore (and the original may have failed to embed because of size issues)
