### ISSUE TITLE
link suggestion

### ISSUE THREAD

**Issue by MrAtoss** [ThePlasmaRailgun/cdn.dlcordapp.com#8]
Hi, coming from reddit, could you add this link to choose from: www.youtube.com/watch?v=vwMuIYPT3c8
it's from the overwatch game, just to troll/meme on some friends

**Comment by cortega729** [comment]
Hey,
Wondering if you could add this link as well: https://www.youtube.com/watch?v=DFtZ0SbWTrg
"Guts Man's Butt"

**Comment by lilyremigia** [comment]
Better yet, just add the ability to give your custom url, if possible

**Comment by fionafibration** [comment]
Custom URL is definitely not happening, I will approve pull requests with any custom links!
